from setuptools import setup, find_packages

import os

def get_version():
    version_path = os.path.join(os.path.dirname(__file__), 'time_balance', 'VERSION')
    with open(version_path, 'r') as f:
        return f.read().strip()

setup(
    name='time-balance',
    version=get_version(),
    description='Control sencillo de jornadas y saldo horario',
    packages=find_packages(),
    include_package_data=True,
    package_data={
        'time_balance': ['VERSION', 'i18n/locales/*.json'],
    },
    install_requires=[
        'rich>=10.0.0',
    ],
    # Entry point para el comando interactivo `time-balance`
    entry_points={
        'console_scripts': [
            'time-balance=time_balance.cli.main:main',
        ],
    },
    author='autogenerated',
    license='GPL-3.0-only',
    classifiers=[
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    ],
)
