from setuptools import setup, find_packages

setup(
    name='time-balance',
    version='0.3.0',
    description='Control sencillo de jornadas y saldo horario',
    packages=find_packages(exclude=("tests",)),
    # Entry point para el comando interactivo `time-balance`
    entry_points={
        'console_scripts': [
            'time-balance=time_balance:main',
        ],
    },
    author='autogenerated',
    license='GPL-3.0-only',
    classifiers=[
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    ],
)
