VERSION = "0.2.0"

# --- CONFIGURACIÓN DE TIEMPO ---
HORAS_BASE = 7
MINUTOS_BASE = 45

# --- PERSISTENCIA ---
ARCHIVO_DATOS = "historial_horas.json"
ENV_HISTORIAL = "HISTORIAL_PATH"

# --- MODOS DE IMPORTACIÓN ---
MODE_MERGE = "merge"
MODE_OVERWRITE = "overwrite"

MODOS_IMPORTACION_VALIDOS = [MODE_MERGE, MODE_OVERWRITE]
