VERSION = "0.2.0"

# --- TIME CONFIGURATION ---
BASE_HOURS = 7
BASE_MINUTES = 45

# --- PERSISTENCE ---
DATA_FILE = "historial_hours.json"
ENV_HISTORIAL = "HISTORIAL_PATH"

# --- IMPORT MODES ---
MODE_MERGE = "merge"
MODE_OVERWRITE = "overwrite"

VALID_IMPORT_MODES = [MODE_MERGE, MODE_OVERWRITE]
